manifest:
  remotes:
    - name: bezmi
      url-base: https://github.com/bezmi
  projects:
    - name: zmk
      remote: bezmi
      revision: multi_peripheral
      import: app/west.yml
  self:
    path: config
